version: "3.8"
#inside services we need to specify all services
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: search_api
    networks:
      springboot-search-net:

  springboot-restful-webservices:
    container_name: springboot-search-restapi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-search-net:
    restart: on-failure

networks:
  springboot-search-net:
